List<String> data=[
  "General Medicine",
  "Internal Medicine",
  " Primary Care",
    "Pediatrics",
  "Obstetrics and Gynecology (OBGYN)",
  "Family Medicine",
  "General Surgery",
  "Preventive Medicine",
  "Dermatology",
  "Occupational & Industrial Medicine",
  "Public Health",
  "Cardiology",
  "Ophthalmology",
  "ENT (Otorhinolaryngology)",
  "Orthopedic Surgery",
  "Pulmonology",
  "Dentistry",
  "Nephrology",
  "Gastroenterology",
  "Endocrinology",
  "Lifestyle Medicine",
  "Infectious Disease",
  "Neurology",
  "Dentistry - Orthodontics",
  "Diabetology",
  "Diet & Nutrition",
  "Oncology - Surgical",
  "Oncology",
  'Emergency Medicine',
  "Cosmetic Surgery",
  "Sports Medicine",
  "Dentistry - Oral Surgery",
  "Aesthetic, Reconstructive & Burn",
  "Urology",
  "Psychiatry",
  "Pain Medicine",
  "Geriatric Medicine",
  "Colorectal Surgery & Proctology",
  "Dentistry - Prosthodontics",
  "Pediatrics - Ambulatory",
  "Anesthesiology",
  "Oncology - Medical",
  "Urgent Care Medicine",
  "Orthopedics - Interventional",
  "Hepatobiliary Surgery",
  "Ophthalmology - Cataracts & Refractive Surgery",
  "Rheumatology",
  "Pediatrics - Adolescent",
  "Plastic Surgery",
  "Hepatology",
  "Allergology & Immunology",
  "OB Sonology",
  "Maxillofacial Surgery",
  "Pediatrics - Pulmonology",
  "Physiatry",
  "Physical Medicine & Rehabilitation",
  "Reproductive Endocrinology & Infertility",
  "Hematology",
  "Otology",
  "Dentistry - Endodontics",
  "Integrative Medicine",
  "Hepato-Pancreato-Biliary Surgery",
  "Cardiology - Interventional",
  "Perinatology",
  "Sleep Medicine",
  "Dentistry - Pediatrics",
  "Neurosurgery",
  "Urology - Interventional",
  "Gastroenterology - Interventional",
  "Orthopedic Surgery - Spine",
  "Psychology",
  "Hospice & Palliative Care",
  "Pediatrics Infectious Disease",
  "Radiology",
  "Vascular Surgery",
  "Orthopedics - Joint Replacement, Hip & Knee",
  "Pediatrics - Nephrology",
  "Pediatrics - Allergy & Immunology",
  "Pediatrics - ENT (Otorhinolaryngology)",
  "Neonatology",
  "Optometry",
  "Lactation Consultant",
  "Venereology",
  "Ophthalmology - Anterior Segment Surgery",
  "Ophthalmology - Retina",
  "Pediatrics - Orthopedics",
  "Acupuncture",
  "Audiology",
  "Oncology - Radiation",
  "Hepatobiliary Surgical Oncology",
  "Ophthalmology - Vitreo-Retinal Surgery",
  "Veterinary",
  "Orthopedic Surgery - Foot & Ankle",
  "Cardiothoracic Surgery",
  "Pediatrics - Gastroenterology",
  "Oncology - Gynecology",
  "Pediatrics - Cardiology",
  "Pediatrics - Neurology",
  "Pulmonology - Interventional",
  "Pediatrics - Urology",
  "Dentistry - Periodontics",
  "Pediatrics - Developmental & Behavioral",
  "Ophthalmology - Glaucoma",
  "Pathology",
  "Pediatrics - Critical Care Medicine",
  "Pediatrics - Hematology",
  "Pediatrics - Surgery",
  "Rheumatology - Interventional",
  "Bariatric Surgery",
  "Dermatopathology",
  "Radiology - Interventional",
  "Nuclear Medicine",
  "Pediatrics - Hematology & Oncology",
  "Pediatrics - Oncology",
  "Podiatry",
  "Pediatrics - Clinical Genetics",
  "Ophthalmology - Ocuplastics and Orbit Surgery",
  "Veterinary Surgery",
  "Pediatrics - Emergency Medicine",
  "Naturopathy",
  "Pancreatic Surgery",
  "Pediatrics - Nuerosurgery",
  "Pediatrics - Opthalmology",
  'Psychiatry - Interventional',
  "Othorhinolaryngology (ENT)",
  'Neurotology',
  "Chiropractic",
  "Opthalmology - Cornea and External Diseases",
  "Opthalmology - Uveitis and Immunology",
  "Pediatrics - Nuerodevelopmental",
  "Transgender Health and Wellness",
  "Pediatrics - Hepatology",
  "Pediatrics - Otology",
  "Psychiatry - Child & Adolescent",
  "Endocrinology - Interventional",
  "Pediatrics - Endocrinology",
  "Pediatrics - Child Protection Specialist",
  "Pediatrics - Rheumatology",
  "Oncology - Hematologic",
  "Toxicology",
  "Oncology - Trophoblastic Diseases",
  "Opthalmology - Opthalmic Pathology",
  "Legal Medicine & Jurisprudence",
  "Thoracic Cardiovascular Surgery",
  "Veterinary Surgeons",
  "Opthalmology - Nuero-Opthalmology",
  "Nephrology - Interventional",
  "Pain Management",
  "Pediatrics - Opthalmology & Strabismus",
  "Surgical Oncologist",
  "Diet / Nutrition",
  "Endodontics",
  "Orthodontics",
  "Pediatric Gastroenterology",
  "Pediatric Orthopedics",
  "Pediatric Pulmonology",
  "Radiation Oncology",
  "Opthalmology - Ocular Oncology",
];