// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR9hJ4ZV6oWFjZs2KjkMdS63SeWX2dMec',
    appId: '1:850354737228:web:6abf2565bad6975a9124e9',
    messagingSenderId: '850354737228',
    projectId: 'med-doc-2d2e9',
    authDomain: 'med-doc-2d2e9.firebaseapp.com',
    storageBucket: 'med-doc-2d2e9.appspot.com',
    measurementId: 'G-3E56Q4VJL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASUx5Z93HMNuX4dl7ErzKmm7qkqw-EN9E',
    appId: '1:850354737228:android:91b0ccbe2182ad939124e9',
    messagingSenderId: '850354737228',
    projectId: 'med-doc-2d2e9',
    storageBucket: 'med-doc-2d2e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCEE-Wv-RKPLTMdfYshSRQekwX3qoNyME',
    appId: '1:850354737228:ios:35230c4243b80b6a9124e9',
    messagingSenderId: '850354737228',
    projectId: 'med-doc-2d2e9',
    storageBucket: 'med-doc-2d2e9.appspot.com',
    iosClientId: '850354737228-0gm97d9vul7l5vpmrn0lv8p7mno0m0hd.apps.googleusercontent.com',
    iosBundleId: 'com.app.meddoc',
  );
}
