// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-fKb9dC0faumJxwBwp0vHj0TGcouirU8',
    appId: '1:538340785905:web:f104acf23125a1f60ff350',
    messagingSenderId: '538340785905',
    projectId: 'meddoc-10c45',
    authDomain: 'meddoc-10c45.firebaseapp.com',
    storageBucket: 'meddoc-10c45.appspot.com',
    measurementId: 'G-E4P4Z2XERL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ_cDJ3wSbBBwMC4pyVVraMmhruN-DA5k',
    appId: '1:538340785905:android:6ad46ff129d12a390ff350',
    messagingSenderId: '538340785905',
    projectId: 'meddoc-10c45',
    storageBucket: 'meddoc-10c45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXfcV-s1WKlQseLtgbqKl-swUNybEr9-s',
    appId: '1:538340785905:ios:4e5eb598a7b7ecdd0ff350',
    messagingSenderId: '538340785905',
    projectId: 'meddoc-10c45',
    storageBucket: 'meddoc-10c45.appspot.com',
    iosClientId:
        '538340785905-24cjt779107no93p96cvkai46eb16kgs.apps.googleusercontent.com',
    iosBundleId: 'com.app.meddoc',
  );
}
